// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lock`, `registry`

/// 本平台是否提供端侧识别实现（Windows = true；其它平台留给后续里程碑）
Future<bool> asrIsAvailable() =>
    RustLib.instance.api.crateApiAsrBridgeAsrIsAvailable();

/// 结构体布局自检：返回一行人类可读的尺寸对照，便于排查 ABI 漂移。
Future<String> asrLayoutSelftest() =>
    RustLib.instance.api.crateApiAsrBridgeAsrLayoutSelftest();

/// 直接对一段 WAV 做端侧识别（不做 VAD 切句），返回识别文本。
/// 用于"模型能不能跑通"的最小验证。
Future<String> asrTranscribePcm16Wav({
  required String modelDir,
  required String libDir,
  required List<int> wavBytes,
  required int numThreads,
}) => RustLib.instance.api.crateApiAsrBridgeAsrTranscribePcm16Wav(
  modelDir: modelDir,
  libDir: libDir,
  wavBytes: wavBytes,
  numThreads: numThreads,
);

/// 默认模型目录（Dart 侧通常显式传目录，这里仅作兜底）
Future<String> asrDefaultModelDir() =>
    RustLib.instance.api.crateApiAsrBridgeAsrDefaultModelDir();

/// 创建端侧引擎（加载模型，几百毫秒到数秒）。返回句柄；失败返回错误文案。
BigInt asrCreate({
  required String modelDir,
  required String libDir,
  required int numThreads,
}) => RustLib.instance.api.crateApiAsrBridgeAsrCreate(
  modelDir: modelDir,
  libDir: libDir,
  numThreads: numThreads,
);

/// 开始一次会话
void asrStart({required BigInt handle}) =>
    RustLib.instance.api.crateApiAsrBridgeAsrStart(handle: handle);

/// 送入一块 PCM（16k/mono/int16 小端）
void asrAcceptPcm16({required BigInt handle, required List<int> pcm}) => RustLib
    .instance
    .api
    .crateApiAsrBridgeAsrAcceptPcm16(handle: handle, pcm: pcm);

/// 收尾：吐出尾段
void asrFlush({required BigInt handle}) =>
    RustLib.instance.api.crateApiAsrBridgeAsrFlush(handle: handle);

/// 取走新识别出来的文本（调用后清空）
String asrTakeText({required BigInt handle}) =>
    RustLib.instance.api.crateApiAsrBridgeAsrTakeText(handle: handle);

/// 释放引擎
void asrDestroy({required BigInt handle}) =>
    RustLib.instance.api.crateApiAsrBridgeAsrDestroy(handle: handle);
