// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'sync_events.dart';

// These functions are ignored because they are not marked as `pub`: `ai_tx_box`, `ai_tx`, `file_tx_box`, `file_tx`, `subscribe_ai`, `subscribe_file`, `subscribe_sync`, `sync_tx_box`, `sync_tx`

/// 触发全局优雅关闭：drop 所有 broadcast 发送端，
/// 事件流循环的 `rx.recv()` 将返回 `Closed` 并退出，释放 frb 运行时。
Future<void> shutdownAll() =>
    RustLib.instance.api.crateApiEventBusShutdownAll();

/// 发布同步进度事件
Future<void> emitSyncProgress({
  required SyncProgressPhase phase,
  required double progress,
  required String message,
}) => RustLib.instance.api.crateApiEventBusEmitSyncProgress(
  phase: phase,
  progress: progress,
  message: message,
);

/// 发布 AI 流式事件
Future<void> emitAiStream({
  required String blockId,
  required String chunk,
  required bool isComplete,
}) => RustLib.instance.api.crateApiEventBusEmitAiStream(
  blockId: blockId,
  chunk: chunk,
  isComplete: isComplete,
);

/// 发布文件同步事件
Future<void> emitFileSync({
  required String filePath,
  required FileSyncEventStatus status,
  required double progress,
}) => RustLib.instance.api.crateApiEventBusEmitFileSync(
  filePath: filePath,
  status: status,
  progress: progress,
);
