// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 返回当前 FFI 契约版本，Dart 端据此路由
Future<int> apiVersion() => RustLib.instance.api.crateApiFfiApiApiVersion();

/// 查询同步引擎当前状态（骨架占位：返回 Idle；真实实现接入 sync 引擎后替换）
Future<String> getSyncStatus() =>
    RustLib.instance.api.crateApiFfiApiGetSyncStatus();

/// 触发一次全量同步（骨架：Mock 空实现）
Future<void> triggerFullSync() =>
    RustLib.instance.api.crateApiFfiApiTriggerFullSync();

/// 查询指定时间戳之后的同步进度事件（轮询版占位）。
///
/// TODO(EventStream)：运行 `flutter_rust_bridge_codegen generate` 生成
/// `SseEncode` 绑定后，增加 `sync_progress_stream(sink: StreamSink<SyncProgressEvent>)`
/// 版本（架构文档 5.3 事件总线），并把 `SyncProgressEvent` 纳入 `rust_input: crate::api`
/// 的可见范围内；届时 Dart 侧用 `Stream` 订阅，无需轮询。
Future<List<String>> syncProgressEventsSince({
  required PlatformInt64 sinceTimestamp,
}) => RustLib.instance.api.crateApiFfiApiSyncProgressEventsSince(
  sinceTimestamp: sinceTimestamp,
);
