// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// AI 流式输出事件
class AiStreamEvent {
  final String blockId;
  final String chunk;
  final bool isComplete;

  const AiStreamEvent({
    required this.blockId,
    required this.chunk,
    required this.isComplete,
  });

  @override
  int get hashCode => blockId.hashCode ^ chunk.hashCode ^ isComplete.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiStreamEvent &&
          runtimeType == other.runtimeType &&
          blockId == other.blockId &&
          chunk == other.chunk &&
          isComplete == other.isComplete;
}

/// 文件同步事件
class FileSyncEvent {
  final String filePath;
  final FileSyncEventStatus status;
  final double progress;

  const FileSyncEvent({
    required this.filePath,
    required this.status,
    required this.progress,
  });

  @override
  int get hashCode => filePath.hashCode ^ status.hashCode ^ progress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileSyncEvent &&
          runtimeType == other.runtimeType &&
          filePath == other.filePath &&
          status == other.status &&
          progress == other.progress;
}

/// 文件同步事件状态
enum FileSyncEventStatus { uploading, downloaded, error }

/// 同步进度事件
class SyncProgressEvent {
  final SyncProgressPhase phase;
  final double progress;
  final String message;

  const SyncProgressEvent({
    required this.phase,
    required this.progress,
    required this.message,
  });

  @override
  int get hashCode => phase.hashCode ^ progress.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncProgressEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          progress == other.progress &&
          message == other.message;
}

/// 同步进度阶段
enum SyncProgressPhase { started, pulling, pushing, uploading, done, error }
